### ISSUE TITLE
Can't get SanPy publish.yml to publish to PyPi?

### ISSUE THREAD

**Issue by cudmore** [cudmore/SanPy#17]
I can't get SanPy published to PyPi? I copied the brightest-path-lib publish.yml and it is failing on all the linux builds and pypi is not updating

1) All the linux build are failing with:

```
line 287, in build_in_container
      raise NonPlatformWheelError()
  cibuildwheel.util.NonPlatformWheelError: 
  cibuildwheel: Build failed because a pure Python wheel was generated.
  
  If you intend to build a pure-Python wheel, you don't need cibuildwheel - use
  `pip wheel -w DEST_DIR .` instead.
  
  If you expected a platform wheel, check your project configuration, or run
  cibuildwheel with CIBW_BUILD_VERBOSITY=1 to view build logs.
```
2) The publish.yml was not triggering when the "Release" workflow finished

I had to modify this ...

```
on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]
    branches: [main]
```

to this ...

```
on: 
  push:
    tags:
    - 'v*'
```
